import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/Cours/components/app-sidebar"
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <SidebarProvider>
       <AppSidebar />
      <main className="flex min-h-screen flex-col w-full">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <SidebarTrigger/>
        
        {children}
      </main>
      </SidebarProvider>
  );
}
